CREATE TABLE PRICES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    BRAND_ID BIGINT,
    START_DATE TIMESTAMP,
    END_DATE TIMESTAMP,
    PRICE_LIST INTEGER,
    PRODUCT_ID BIGINT,
    PRIORITY INTEGER,
    PRICE DECIMAL(10,2),
    CURR VARCHAR(3)
);